create table public.mcqs_p3 (
  main_id bigint generated by default as identity not null,
  id bigint null,
  question_text text null,
  option_a text null,
  option_b text null,
  option_c text null,
  option_d text null,
  correct_answer text null,
  stylized_option text null,
  tag text null,
  year integer null,
  difficulty text null,
  subject text null,
  related_concepts text null,
  explanation jsonb null,
  gemini_answer text null,
  failed_explanation jsonb null,
  failed_reason text null,
  is flashcard text null,
  new_tag text null,
  constraint mcqs_p3_pkey primary key (main_id)
) TABLESPACE pg_default;

create index IF not exists idx_mcqs_p3_tag on public.mcqs_p3 using btree (tag) TABLESPACE pg_default;

create index IF not exists idx_mcqs_p3_tag_main_id on public.mcqs_p3 using btree (tag, main_id) TABLESPACE pg_default;

create index IF not exists idx_mcqs_p3_main_id on public.mcqs_p3 using btree (main_id) TABLESPACE pg_default;

create index IF not exists idx_mcqs_p3_year on public.mcqs_p3 using btree (year) TABLESPACE pg_default;
