create table public.mcqs_p1 (
  id bigint null,
  question_text text null,
  option_a text null,
  option_b text null,
  option_c text null,
  option_d text null,
  correct_answer text null,
  tag text null,
  year bigint null,
  difficulty text null,
  subject text null,
  related_concepts text null,
  main_id bigint generated by default as identity not null,
  explanation jsonb null,
  gemini_answer text null,
  failed_explanation jsonb null,
  failed_reason text null,
  is_flashcard text null,
  new_tag text null,
  constraint mcqs_p1_pkey primary key (main_id)
) TABLESPACE pg_default;

create index IF not exists idx_mcqs_p1_tag on public.mcqs_p1 using btree (tag) TABLESPACE pg_default;

create index IF not exists idx_mcqs_p1_tag_main_id on public.mcqs_p1 using btree (tag, main_id) TABLESPACE pg_default;

create index IF not exists idx_mcqs_p1_main_id on public.mcqs_p1 using btree (main_id) TABLESPACE pg_default;

create index IF not exists idx_mcqs_p1_year on public.mcqs_p1 using btree (year) TABLESPACE pg_default;
