create table public.nce_chapter_weightages (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  paper text null,
  chapter_name text null,
  weightage_percentage integer null,
  constraint nce_chapter_weightages_pkey primary key (id),
  constraint nce_chapter_weightages_id_key unique (id)
) TABLESPACE pg_default;
