create table public.questions (
  id bigint generated by default as identity not null,
  "NCE_number" smallint null,
  question_number text null,
  paper text null,
  question jsonb null,
  flash_explanation jsonb null,
  tags text null,
  difficulty_level text null,
  explanation jsonb null,
  constraint questions_pkey2 primary key (id)
) TABLESPACE pg_default;
